disabled_rules: # Default Rules에서 비활성화할 규칙
  
  # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
  - trailing_whitespace
    
  # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
  - force_cast
    
  # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
  - force_unwrapping
    
  # 한 줄의 길이를 제한합니다.
  - line_length
  
  # 아무 것도 재정의 하지 않는 함수를 제한합니다. https://realm.github.io/SwiftLint/unneeded_override.html
  - unneeded_override

opt_in_rules: # Default Rules에서 활성화할 규칙
  
  # Imports should be sorted
  - sorted_imports
  
  # 들여쓰기의 길이를 고정합니다 https://realm.github.io/SwiftLint/indentation_width.html
  - indentation_width

# 들여쓰기를 2칸으로 고정합니다 https://realm.github.io/SwiftLint/indentation_width.html
indentation_width:
  indentation_width: 2

type_body_length: 
  warning: 500
  error: 600
